# Generated by Django 4.1.3 on 2022-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=40)),
            ],
        ),
    ]
