# Generated by Django 4.1.3 on 2022-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Autor', models.CharField(max_length=30)),
                ('Salida', models.DateField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
            ],
        ),
    ]
