# Generated by Django 4.1.3 on 2022-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_libros_venta_id_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='users',
            new_name='user',
        ),
    ]
