# Generated by Django 4.1.3 on 2022-12-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_users_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
