# Generated by Django 4.1.3 on 2022-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20221128_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
